### ISSUE TITLE
Running unit_commitment.py standalone

### ISSUE THREAD

**Issue by MajidSKhoshghalb** [grid-parity-exchange/Egret#141]
Hi,
I tried to run unit_commitment.py in a standalone way by un-commenting the main at the end.
The first error is that there is no _read_from_json(file)_ in **ModelData**, only read(file) method which is a typo.
The second error after fixing the above:
_File "c:\users\me\desktop\python-test\egret-master\egret\model_library\unit_commitment\uc_model_generator.py", line 100, in _generate_model
    baseMVA = model_data.data['system']['baseMVA']
KeyError: 'baseMVA'_

I fixed this by adding an instance (_self_) version of the class method read(file) to **ModelData**. Any idea?

Thanks in advance!

**Comment by bknueven** [comment]
`ModelData.read` is meant to be used as a class method -- see the examples in [examples/unit_commitment](https://github.com/grid-parity-exchange/Egret/tree/master/examples/unit_commitment).

The `ModelData` method `read_from_json` was removed by #97, but never updated in this commented out code. Because users tend to find it useful, its is uncommented as part of #137 updated for the changes made by #97.

**Comment by MajidSKhoshghalb** [comment]
Thanks for your detailed description.
