### ISSUE TITLE
SOC relaxation directly

### ISSUE THREAD

**Issue by DLWoodruff** [grid-parity-exchange/Egret#145]
It would be good to have a convex relaxation of AC as a model itself.

**Comment by anyacastillo** [comment]
Agreed. This may suffice: https://github.com/anyacastillo/Egret/blob/redly_aux/egret/models/ac_relaxations.py (line 36).

**Comment by michaelbynum** [comment]
You mean you don't want to have to "generate" the relaxation? Can you elaborate? What is the motivation?

**Comment by bknueven** [comment]
I believe @DLWoodruff is having numerical issues with the AC relaxations. Maybe this can be dealt with my exposing the fbbt options? The assumption behind creating the SOC relaxation directly is that it may be more numerically stable than a transformation.

**Comment by michaelbynum** [comment]
@DLWoodruff You may want to try:

```
create_soc_relaxation(md, use_linear_relaxation=False)
```

The default uses a linear relaxation, with a linear outer-approximation of the SOC, which is where your numerical issues are probably coming from.

**Comment by jeanpaulwatson** [comment]
When @DLWoodruff and I were diagnosing, we isolated the issue to very small coefficients (like 1e-16) in constraints generated by Coramin. It's reminiscent of similar issues we encountered early in the Pyomo piecewise implementation. The latter were fixed by thresholding / collapsing too-near points.

**Comment by michaelbynum** [comment]
I think this can be closed now?
