### ISSUE TITLE
Mipgap to None when invoking _solve_model from solve_dcopf

### ISSUE THREAD

**Issue by jeanpaulwatson** [grid-parity-exchange/Egret#160]
This is minor, but also easy to fix if agreed upon.

The function solve_dcopf in models/dcopf.py calls _solve_model (in common/solver_interface.py) to solve the DCOPF model once constructed. The default mipgap in _solve_model is 0.001. Further, solve_dcopf does not over-ride, even though it's continuous problem. I am proposing to set the mipgap keyword argument in the call to _solve_model from solve_dcopf to None, mainly to stop people from wondering why a mipgap is set for a continuous problem, when staring at the traces.

More generally, why is the mipgap default to something other than None in _solve_model? Especially given that it's distinct (I think) from at least the Gurobi default.

**Comment by bknueven** [comment]
The unit commitment top-level solve call already has a default: https://github.com/grid-parity-exchange/Egret/blob/e2ee343296a18d1d3e23b75e182ccfb9940376b6/egret/models/unit_commitment.py#L1506

I think we should change the default mipgap in `_solve_model` to `None`, as this will be generally true of all the OPF models, and I suspect this was done originally before the higher-level solve functions were constructed.

We set a non-default mipgap because the open-source solvers set it to 0 by default, and not seeing this as good for our users, I set it to something moderately industry-standard for unit commitment, 0.1%.

**Comment by jeanpaulwatson** [comment]
Sounds good - I'll work on a PR now.

**Comment by bknueven** [comment]
Closed by #161.
