### ISSUE TITLE
Extending PWL Costs

### ISSUE THREAD

**Issue by bknueven** [grid-parity-exchange/Egret#235]
The PWL cost curve handling introduced in #227 fail when the lowest power point on the curve is greater than or equal p_max and when the highest power point on the curve is less than or equal to p_min.

To resolve this, we could either:
1. Determine this is a user error, in which case we should throw a proper error.
2. Handle this case automatically. We already extend the PWL cost curve beyond its given bounds, so extending it in this case is perhaps not the *worst* thing.

**Comment by DLWoodruff** [comment]
I need a decision on this issue sooner rather than later. It is a simple question, but I can't honestly say I know what is the right answer. BTW:  I think he means "when the lowest power point on the cost curve is *greater than* p_max " But anyway, the question is: should Egret silently extend the piecewise cost curve?
