### ISSUE TITLE
Path issue when running generate_graphs.py for RTS-GMLC test case

### ISSUE THREAD

**Issue by jwatsonnm** [grid-parity-exchange/Egret#37]
For @rconcep - I suspect you want to restore the code in the main() in generate_graphs.py that is presently commented out - which would use the built-in test data in egret/models/tests/uc_test_instances. I would like to retain the general test functionality in this module, as it's a nice quick+dirty way to generate a graph - and provide an example of how to interact with the library.

**Comment by rconcep** [comment]
> 
> 
> For @rconcep - I suspect you want to restore the code in the main() in generate_graphs.py that is presently commented out - which would use the built-in test data in egret/models/tests/uc_test_instances. I would like to retain the general test functionality in this module, as it's a nice quick+dirty way to generate a graph - and provide an example of how to interact with the library.

Sure, that can be done. I didn't really expect that main() to be used except for development testing. I'm thinking the block for the RTS-GMLC test should be cleaned out eventually since it is dependent on having that repo cloned to your machine. It's assuming that the RTS-GMLC repo is cloned to the same dir as the EGRET repo as my machines are all configured. It was a useful test since the uc_test_instances seem to only have gas generation whereas the RTS-GMLC case has a more diverse set of stack components.

Path issues are likely because my IDE was set up to run files with the cwd set to the repo root. I think it can be fixed by checking the current file's location and doing relative pathing from that.

**Comment by jwatsonnm** [comment]
I realize I'm asking for a co-opting of something that was not intended to be released. I just think that having such snippets to run canned examples will be very useful for demonstration/visualization.

**Comment by bknueven** [comment]
This was addressed by #41.
